export const seedData = {
  users: [],
  sessions: [],
  patient: {
    name: 'Sarah Mitchell',
    age: 34,
    identifier: 'Health ID: 100-234-567',
    location: 'Health Center 1',
    primaryCondition: 'Preventive care plan',
    careTeam: 'Dr. James Wilson and Dr. Emily Chen',
    insurance: 'HealthCare Plus',
    preferredLanguage: 'English',
    emergencyContact: 'Michael Mitchell',
  },
  preferences: {
    shareRecords: true,
  },
  tasks: [
    {
      id: 'task-1',
      label: 'Confirm telehealth visit consent',
      due: 'Today, 4:00 PM',
      owner: 'Patient',
      priority: 'High',
      completed: false,
    },
    {
      id: 'task-2',
      label: 'Upload fasting glucose readings',
      due: 'Tomorrow',
      owner: 'Care team',
      priority: 'Medium',
      completed: true,
    },
    {
      id: 'task-3',
      label: 'Review updated metformin instructions',
      due: 'June 2',
      owner: 'Pharmacy',
      priority: 'Low',
      completed: false,
    },
  ],
  appointments: [
    {
      id: 'apt-cardiology-1',
      service: 'Cardiology follow-up',
      clinician: 'Dr. Sarah Jenkins',
      provider: 'Dr. Sarah Jenkins',
      date: 'Oct 26, 2023',
      time: '10:30 AM (Thursday)',
      department: 'Cardiology',
      location: 'Main Clinic, Suite 402',
      initials: 'SJ',
      type: 'In person',
      status: 'Confirmed',
      statusGroup: 'Upcoming',
      action: 'Details',
      secondaryAction: 'Cancel',
    },
    {
      id: 'apt-gastro-1',
      service: 'Gastroenterology consult',
      clinician: 'Dr. Robert Miller',
      provider: 'Dr. Robert Miller',
      date: 'Nov 02, 2023',
      time: '02:15 PM (Thursday)',
      department: 'Gastroenterology',
      location: 'West Wing, Room 12-B',
      initials: 'RM',
      type: 'In person',
      status: 'Confirmed',
      statusGroup: 'Upcoming',
      action: 'Details',
      secondaryAction: 'Cancel',
    },
    {
      id: 'apt-lab-1',
      service: 'Lab Work',
      clinician: 'Lab Technician',
      provider: 'Lab Technician',
      date: 'Nov 15, 2023',
      time: '08:00 AM (Wednesday)',
      department: 'Diagnostics',
      location: 'Central Lab, Floor 1',
      initials: 'LW',
      type: 'Diagnostics',
      status: 'Pending',
      statusGroup: 'Upcoming',
      action: 'Instructions',
      secondaryAction: 'Reschedule',
    },
    {
      id: 'apt-physical-past',
      service: 'Annual Physical',
      clinician: 'Dr. James Wilson',
      provider: 'Dr. James Wilson',
      date: 'Oct 12, 2023',
      time: '09:00 AM (Thursday)',
      department: 'General Medicine',
      location: 'Health Center 1',
      initials: 'JW',
      type: 'In person',
      status: 'Completed',
      statusGroup: 'Past',
      action: 'Summary',
      secondaryAction: 'Message',
    },
    {
      id: 'apt-dental-cancelled',
      service: 'Dental Cleaning',
      clinician: 'Dr. Emily Chen',
      provider: 'Dr. Emily Chen',
      date: 'Oct 19, 2023',
      time: '02:15 PM (Thursday)',
      department: 'Dental',
      location: 'Suite 405',
      initials: 'EC',
      type: 'In person',
      status: 'Cancelled',
      statusGroup: 'Cancelled',
      action: 'Details',
      secondaryAction: 'Reschedule',
    },
  ],
  appointmentRequests: [],
  medications: [
    {
      name: 'Metformin XR',
      dose: '500 mg',
      schedule: '2 tablets with evening meal',
      refill: '12 days left',
      status: 'Active',
    },
    {
      name: 'Atorvastatin',
      dose: '20 mg',
      schedule: '1 tablet nightly',
      refill: 'Refill ready',
      status: 'Active',
    },
    {
      name: 'Vitamin D3',
      dose: '1000 IU',
      schedule: '1 tablet daily',
      refill: '45 days left',
      status: 'Optional',
    },
  ],
  preferredPharmacy: {
    id: 'pharmacy-cvs-04322',
    name: 'CVS Pharmacy #04322',
    addressLine1: '123 Health Ave, Medical District',
    addressLine2: 'Boston, MA 02115',
    phone: '(617) 555-0199',
    hours: 'Open 24 Hours',
    isPreferred: true,
    updatedAt: '2024-01-12T10:00:00.000Z',
  },
  prescriptions: [
    {
      id: 'rx-lisinopril',
      name: 'Lisinopril 10 mg Tablet',
      detail: 'Oral - Rx: 4422991-A',
      frequency: 'Once daily',
      started: 'Jan 12, 2024',
      refillCount: '0 left',
      refillDetail: 'Needs Authorization',
      status: 'Refill Due',
    },
    {
      id: 'rx-metformin',
      name: 'Metformin 500 mg ER',
      detail: 'Oral - Rx: 4422991-B',
      frequency: 'Twice daily with meals',
      started: 'Mar 05, 2024',
      refillCount: '2 left',
      refillDetail: 'Expires Sep 2024',
      status: 'Active',
    },
    {
      id: 'rx-atorvastatin',
      name: 'Atorvastatin 20 mg Tablet',
      detail: 'Oral - Rx: 4422991-C',
      frequency: 'Once daily at bedtime',
      started: 'Feb 20, 2024',
      refillCount: '1 left',
      refillDetail: 'Expires Aug 2024',
      status: 'Active',
    },
    {
      id: 'rx-albuterol',
      name: 'Albuterol HFA Inhaler',
      detail: 'Inhalation - Rx: 4422991-D',
      frequency: 'As needed for SOB',
      started: 'Jan 10, 2024',
      refillCount: '3 left',
      refillDetail: 'Expires Jan 2025',
      status: 'Active',
    },
    {
      id: 'rx-amoxicillin',
      name: 'Amoxicillin 500 mg',
      detail: 'Oral - Rx: Pending',
      frequency: 'Every 8 hours',
      started: '-',
      refillCount: '-',
      refillDetail: '',
      status: 'Pending Request',
    },
  ],
  refillRequests: [],
  medicationRequests: [],
  billing: {
    outstandingBalance: 1248.5,
    paymentStatus: 'Due',
    dueDate: 'Oct 25',
    breakdown: {
      consultation: 450,
      laboratory: 320.5,
      radiology: 478,
      pharmacy: 0,
    },
    paymentMethods: [
      {
        id: 'method-visa',
        type: 'Card',
        label: 'Visa **** 4242',
        detail: 'Expires 12/26',
        isDefault: true,
      },
      {
        id: 'method-bank',
        type: 'Bank',
        label: 'Chase Savings **** 1902',
        detail: 'Direct Deposit',
      },
    ],
    invoices: [
      {
        id: 'INV-2023-089',
        date: 'Oct 12, 2023',
        description: 'Annual Wellness Exam - Dr. Smith',
        amount: 450,
        status: 'Overdue',
      },
      {
        id: 'INV-2023-082',
        date: 'Sep 28, 2023',
        description: 'Blood Panel & Diagnostics',
        amount: 185.2,
        status: 'Paid',
      },
      {
        id: 'INV-2023-077',
        date: 'Sep 15, 2023',
        description: 'Pharmacy - Antibiotics Refill',
        amount: 34.5,
        status: 'Pending',
      },
      {
        id: 'INV-2023-065',
        date: 'Aug 22, 2023',
        description: 'Radiology - Chest X-Ray',
        amount: 210,
        status: 'Paid',
      },
    ],
    payments: [],
    statements: [
      {
        id: 'statement-2023-10',
        invoiceIds: ['INV-2023-089', 'INV-2023-082', 'INV-2023-077', 'INV-2023-065'],
        period: 'October 2023',
        generatedAt: '2023-10-25T12:00:00.000Z',
        status: 'Ready',
      },
    ],
    resources: [
      {
        id: 'tax-form-1095-b',
        title: 'Tax Form 1095-B',
        detail: '2023 Annual Report',
      },
      {
        id: 'insurance-policy',
        title: 'Insurance Policy',
        detail: 'Current: BlueShield Gold',
      },
    ],
  },
  profileSettings: {
    fullName: 'Johnathan Alexander Smith',
    email: 'j.smith@medical-portal.org',
    phone: '+1 (555) 012-3456',
    dateOfBirth: '05/12/1985',
    address: '742 Evergreen Terrace, Springfield, OR 97403',
    language: 'English (US)',
    timezone: '(GMT-08:00) Pacific Time',
  },
  accountStatus: {
    profileCompletion: 92,
    twoFactorEnabled: true,
    lastLogin: 'Oct 24, 2023 - 08:42 AM',
    privacyNotice: 'Ensure your residential address is current for mailing laboratory results and official health documentation.',
  },
  insuranceDetails: {
    primaryProvider: 'BlueCross BlueShield',
    memberId: 'BCBS-992033481',
    groupNumber: 'TX-9001-ALPHA',
    policyHolder: 'Self (Johnathan Smith)',
    activeThrough: '12/2024',
    verifiedAt: 'Oct 01, 2023',
  },
  emergencyContacts: [
    {
      id: 'contact-sarah-smith',
      name: 'Sarah Smith',
      relationship: 'Spouse',
      primaryPhone: '(555) 012-9988',
      alternatePhone: '-',
      access: 'Full Proxy',
    },
    {
      id: 'contact-robert-wilson',
      name: 'Robert Wilson',
      relationship: 'Close Friend',
      primaryPhone: '(555) 123-4567',
      alternatePhone: '(555) 765-4321',
      access: 'Emergency Only',
    },
  ],
  labResults: [
    { label: 'Glucose, Fasting', value: 94, unit: 'mg/dL', range: '65 - 99 mg/dL', tone: 'good' },
    { label: 'Cholesterol, Total', value: 210, unit: 'mg/dL', range: '< 200 mg/dL', tone: 'warning' },
    { label: 'Hemoglobin A1c', value: 5.4, unit: '%', range: '4.8 - 5.6 %', tone: 'good' },
    { label: 'Vitamin D, 25-OH', value: 28, unit: 'ng/mL', range: '30 - 100 ng/mL', tone: 'warning' },
  ],
  messages: [
    {
      id: 'msg-1',
      from: 'Dr. Sarah Jenkins',
      subject: 'Lab Results Follow-up',
      preview: 'I have reviewed your blood work from Monday.',
      time: '10:24 AM',
    },
    {
      id: 'msg-2',
      from: 'Nursing Team',
      subject: 'Prescription Refill Request',
      preview: 'Your request for Lipitor has been sent to the pharmacy team.',
      time: 'Yesterday',
    },
  ],
  messageConversations: [
    {
      id: 'conv-sarah-jenkins',
      participantName: 'Dr. Sarah Jenkins',
      participantRole: 'Internal Medicine',
      activeNow: true,
      subject: 'Lab Results Follow-up',
      preview: 'I have reviewed your blood work from Monday.',
      time: '10:24 AM',
      unread: false,
      resolved: false,
      messages: [
        {
          id: 'thread-msg-1',
          direction: 'outbound',
          body: 'Hello Dr. Jenkins, I received my blood test results on the portal this morning. Most values seem normal, but I noticed my LDL cholesterol is higher than it was last year. Should I be concerned or adjust my medication?',
          sentAtLabel: '9:15 AM',
          createdAt: '2024-10-14T09:15:00.000Z',
          read: true,
        },
        {
          id: 'thread-msg-2',
          direction: 'inbound',
          body: "I have reviewed your blood work from Monday and noticed the slight increase as well. At 142 mg/dL, it is above our target for you, but not in the critical range yet. I'd like to try adjusting your diet for the next 3 months before we consider increasing your Atorvastatin dosage.\n\nI've attached a Mediterranean diet guide that has shown great success with my patients. Let's schedule a follow-up lab in January.",
          sentAtLabel: '10:24 AM',
          createdAt: '2024-10-14T10:24:00.000Z',
          labReference: {
            label: 'Lab Result Reference',
            name: 'Lipid Panel (LDL)',
            value: '142 mg/dL',
          },
          attachment: {
            fileName: 'Dietary_Guidelines_Lipid_Control.pdf',
            size: '2.4 MB',
          },
        },
      ],
    },
    {
      id: 'conv-nursing-team',
      participantName: 'Nursing Team',
      participantRole: 'Care Coordination',
      activeNow: false,
      subject: 'Prescription Refill Request',
      preview: 'Your request for Lipitor has been sent to the pharmacy team.',
      time: 'Yesterday',
      unread: true,
      resolved: false,
      messages: [
        {
          id: 'thread-msg-3',
          direction: 'inbound',
          body: 'Your request for Lipitor has been sent to the pharmacy team. We will notify you when the refill is approved.',
          sentAtLabel: 'Yesterday',
          createdAt: '2024-10-13T14:18:00.000Z',
        },
      ],
    },
    {
      id: 'conv-michael-chen',
      participantName: 'Dr. Michael Chen',
      participantRole: 'Surgery',
      activeNow: false,
      subject: 'Follow-up: Surgery Prep',
      preview: 'Please remember to fast for 12 hours prior to your appointment.',
      time: 'Oct 12',
      unread: false,
      resolved: true,
      messages: [
        {
          id: 'thread-msg-4',
          direction: 'inbound',
          body: 'Please remember to fast for 12 hours prior to your appointment and bring your medication list.',
          sentAtLabel: 'Oct 12',
          createdAt: '2024-10-12T08:30:00.000Z',
        },
      ],
    },
    {
      id: 'conv-billing',
      participantName: 'Billing Department',
      participantRole: 'Patient Accounts',
      activeNow: false,
      subject: 'Statement Available',
      preview: 'Your October billing statement is now available.',
      time: 'Oct 10',
      unread: false,
      resolved: false,
      messages: [
        {
          id: 'thread-msg-5',
          direction: 'inbound',
          body: 'Your October billing statement is now available in the patient portal.',
          sentAtLabel: 'Oct 10',
          createdAt: '2024-10-10T11:00:00.000Z',
        },
      ],
    },
  ],
  documents: [
    {
      id: 'doc-1',
      name: 'Continuity of care document',
      category: 'Summary',
      updated: 'May 29, 2026',
      status: 'Ready',
    },
    {
      id: 'doc-2',
      name: 'A1c laboratory report',
      category: 'Labs',
      updated: 'May 27, 2026',
      status: 'New',
    },
  ],
};
