export const seedData = {
  users: [],
  sessions: [],
  patient: {
    name: 'Sarah Mitchell',
    age: 34,
    identifier: 'Health ID: 100-234-567',
    location: 'Health Center 1',
    primaryCondition: 'Preventive care plan',
    careTeam: 'Dr. James Wilson and Dr. Emily Chen',
    insurance: 'HealthCare Plus',
    preferredLanguage: 'English',
    emergencyContact: 'Michael Mitchell',
  },
  preferences: {
    shareRecords: true,
  },
  tasks: [
    {
      id: 'task-1',
      label: 'Confirm telehealth visit consent',
      due: 'Today, 4:00 PM',
      owner: 'Patient',
      priority: 'High',
      completed: false,
    },
    {
      id: 'task-2',
      label: 'Upload fasting glucose readings',
      due: 'Tomorrow',
      owner: 'Care team',
      priority: 'Medium',
      completed: true,
    },
    {
      id: 'task-3',
      label: 'Review updated metformin instructions',
      due: 'June 2',
      owner: 'Pharmacy',
      priority: 'Low',
      completed: false,
    },
  ],
  appointments: [
    {
      id: 'apt-cardiology-1',
      service: 'Cardiology follow-up',
      clinician: 'Dr. Sarah Jenkins',
      provider: 'Dr. Sarah Jenkins',
      date: 'Oct 26, 2023',
      time: '10:30 AM (Thursday)',
      department: 'Cardiology',
      location: 'Main Clinic, Suite 402',
      initials: 'SJ',
      type: 'In person',
      status: 'Confirmed',
      statusGroup: 'Upcoming',
      action: 'Details',
      secondaryAction: 'Cancel',
    },
    {
      id: 'apt-gastro-1',
      service: 'Gastroenterology consult',
      clinician: 'Dr. Robert Miller',
      provider: 'Dr. Robert Miller',
      date: 'Nov 02, 2023',
      time: '02:15 PM (Thursday)',
      department: 'Gastroenterology',
      location: 'West Wing, Room 12-B',
      initials: 'RM',
      type: 'In person',
      status: 'Confirmed',
      statusGroup: 'Upcoming',
      action: 'Details',
      secondaryAction: 'Cancel',
    },
    {
      id: 'apt-lab-1',
      service: 'Lab Work',
      clinician: 'Lab Technician',
      provider: 'Lab Technician',
      date: 'Nov 15, 2023',
      time: '08:00 AM (Wednesday)',
      department: 'Diagnostics',
      location: 'Central Lab, Floor 1',
      initials: 'LW',
      type: 'Diagnostics',
      status: 'Pending',
      statusGroup: 'Upcoming',
      action: 'Instructions',
      secondaryAction: 'Reschedule',
    },
    {
      id: 'apt-physical-past',
      service: 'Annual Physical',
      clinician: 'Dr. James Wilson',
      provider: 'Dr. James Wilson',
      date: 'Oct 12, 2023',
      time: '09:00 AM (Thursday)',
      department: 'General Medicine',
      location: 'Health Center 1',
      initials: 'JW',
      type: 'In person',
      status: 'Completed',
      statusGroup: 'Past',
      action: 'Summary',
      secondaryAction: 'Message',
    },
    {
      id: 'apt-dental-cancelled',
      service: 'Dental Cleaning',
      clinician: 'Dr. Emily Chen',
      provider: 'Dr. Emily Chen',
      date: 'Oct 19, 2023',
      time: '02:15 PM (Thursday)',
      department: 'Dental',
      location: 'Suite 405',
      initials: 'EC',
      type: 'In person',
      status: 'Cancelled',
      statusGroup: 'Cancelled',
      action: 'Details',
      secondaryAction: 'Reschedule',
    },
  ],
  appointmentRequests: [],
  medications: [
    {
      name: 'Metformin XR',
      dose: '500 mg',
      schedule: '2 tablets with evening meal',
      refill: '12 days left',
      status: 'Active',
    },
    {
      name: 'Atorvastatin',
      dose: '20 mg',
      schedule: '1 tablet nightly',
      refill: 'Refill ready',
      status: 'Active',
    },
    {
      name: 'Vitamin D3',
      dose: '1000 IU',
      schedule: '1 tablet daily',
      refill: '45 days left',
      status: 'Optional',
    },
  ],
  preferredPharmacy: {
    id: 'pharmacy-cvs-04322',
    name: 'CVS Pharmacy #04322',
    addressLine1: '123 Health Ave, Medical District',
    addressLine2: 'Boston, MA 02115',
    phone: '(617) 555-0199',
    hours: 'Open 24 Hours',
    isPreferred: true,
    updatedAt: '2024-01-12T10:00:00.000Z',
  },
  prescriptions: [
    {
      id: 'rx-lisinopril',
      name: 'Lisinopril 10 mg Tablet',
      detail: 'Oral - Rx: 4422991-A',
      frequency: 'Once daily',
      started: 'Jan 12, 2024',
      refillCount: '0 left',
      refillDetail: 'Needs Authorization',
      status: 'Refill Due',
    },
    {
      id: 'rx-metformin',
      name: 'Metformin 500 mg ER',
      detail: 'Oral - Rx: 4422991-B',
      frequency: 'Twice daily with meals',
      started: 'Mar 05, 2024',
      refillCount: '2 left',
      refillDetail: 'Expires Sep 2024',
      status: 'Active',
    },
    {
      id: 'rx-atorvastatin',
      name: 'Atorvastatin 20 mg Tablet',
      detail: 'Oral - Rx: 4422991-C',
      frequency: 'Once daily at bedtime',
      started: 'Feb 20, 2024',
      refillCount: '1 left',
      refillDetail: 'Expires Aug 2024',
      status: 'Active',
    },
    {
      id: 'rx-albuterol',
      name: 'Albuterol HFA Inhaler',
      detail: 'Inhalation - Rx: 4422991-D',
      frequency: 'As needed for SOB',
      started: 'Jan 10, 2024',
      refillCount: '3 left',
      refillDetail: 'Expires Jan 2025',
      status: 'Active',
    },
    {
      id: 'rx-amoxicillin',
      name: 'Amoxicillin 500 mg',
      detail: 'Oral - Rx: Pending',
      frequency: 'Every 8 hours',
      started: '-',
      refillCount: '-',
      refillDetail: '',
      status: 'Pending Request',
    },
  ],
  refillRequests: [],
  medicationRequests: [],
  billing: {
    outstandingBalance: 1248.5,
    paymentStatus: 'Due',
    dueDate: 'Oct 25',
    breakdown: {
      consultation: 450,
      laboratory: 320.5,
      radiology: 478,
      pharmacy: 0,
    },
    paymentMethods: [
      {
        id: 'method-visa',
        type: 'Card',
        label: 'Visa **** 4242',
        detail: 'Expires 12/26',
        isDefault: true,
      },
      {
        id: 'method-bank',
        type: 'Bank',
        label: 'Chase Savings **** 1902',
        detail: 'Direct Deposit',
      },
    ],
    invoices: [
      {
        id: 'INV-2023-089',
        date: 'Oct 12, 2023',
        description: 'Annual Wellness Exam - Dr. Smith',
        amount: 450,
        status: 'Overdue',
      },
      {
        id: 'INV-2023-082',
        date: 'Sep 28, 2023',
        description: 'Blood Panel & Diagnostics',
        amount: 185.2,
        status: 'Paid',
      },
      {
        id: 'INV-2023-077',
        date: 'Sep 15, 2023',
        description: 'Pharmacy - Antibiotics Refill',
        amount: 34.5,
        status: 'Pending',
      },
      {
        id: 'INV-2023-065',
        date: 'Aug 22, 2023',
        description: 'Radiology - Chest X-Ray',
        amount: 210,
        status: 'Paid',
      },
    ],
    payments: [],
    statements: [
      {
        id: 'statement-2023-10',
        invoiceIds: ['INV-2023-089', 'INV-2023-082', 'INV-2023-077', 'INV-2023-065'],
        period: 'October 2023',
        generatedAt: '2023-10-25T12:00:00.000Z',
        status: 'Ready',
      },
    ],
    resources: [
      {
        id: 'tax-form-1095-b',
        title: 'Tax Form 1095-B',
        detail: '2023 Annual Report',
      },
      {
        id: 'insurance-policy',
        title: 'Insurance Policy',
        detail: 'Current: BlueShield Gold',
      },
    ],
  },
  profileSettings: {
    fullName: 'Johnathan Alexander Smith',
    email: 'j.smith@medical-portal.org',
    phone: '+1 (555) 012-3456',
    dateOfBirth: '05/12/1985',
    address: '742 Evergreen Terrace, Springfield, OR 97403',
    language: 'English (US)',
    timezone: '(GMT-08:00) Pacific Time',
  },
  accountStatus: {
    profileCompletion: 92,
    twoFactorEnabled: true,
    lastLogin: 'Oct 24, 2023 - 08:42 AM',
    privacyNotice: 'Ensure your residential address is current for mailing laboratory results and official health documentation.',
  },
  insuranceDetails: {
    primaryProvider: 'BlueCross BlueShield',
    memberId: 'BCBS-992033481',
    groupNumber: 'TX-9001-ALPHA',
    policyHolder: 'Self (Johnathan Smith)',
    activeThrough: '12/2024',
    verifiedAt: 'Oct 01, 2023',
  },
  emergencyContacts: [
    {
      id: 'contact-sarah-smith',
      name: 'Sarah Smith',
      relationship: 'Spouse',
      primaryPhone: '(555) 012-9988',
      alternatePhone: '-',
      access: 'Full Proxy',
    },
    {
      id: 'contact-robert-wilson',
      name: 'Robert Wilson',
      relationship: 'Close Friend',
      primaryPhone: '(555) 123-4567',
      alternatePhone: '(555) 765-4321',
      access: 'Emergency Only',
    },
  ],
  labResults: [
    { label: 'Glucose, Fasting', value: 94, unit: 'mg/dL', range: '65 - 99 mg/dL', tone: 'good' },
    { label: 'Cholesterol, Total', value: 210, unit: 'mg/dL', range: '< 200 mg/dL', tone: 'warning' },
    { label: 'Hemoglobin A1c', value: 5.4, unit: '%', range: '4.8 - 5.6 %', tone: 'good' },
    { label: 'Vitamin D, 25-OH', value: 28, unit: 'ng/mL', range: '30 - 100 ng/mL', tone: 'warning' },
  ],
  clinicalNotes: [
    {
      id: 'note-post-op',
      type: 'Follow-up Visit',
      date: 'Oct 12, 2023',
      title: 'Post-operative Management',
      text: 'Patient reports significant reduction in abdominal pain. Surgical incision site is healing well with no signs of infection or erythema.',
    },
    {
      id: 'note-med-review',
      type: 'Telehealth',
      date: 'Sep 28, 2023',
      title: 'Medication Review',
      text: 'Discussed adjustment to Metformin dosage. Patient experiencing mild GI distress. Suggested evening dosing with food and continued monitoring.',
    },
  ],
  immunizations: [
    {
      id: 'imm-influenza',
      title: 'Influenza (Seasonal)',
      last: 'Last: Oct 02, 2023',
      doses: '2 doses',
      status: 'Up to date',
      tone: 'green',
    },
    {
      id: 'imm-covid-booster',
      title: 'COVID-19 Booster',
      last: 'Last: Jan 15, 2023',
      doses: '3 doses',
      status: 'Due Jan 2024',
      tone: 'yellow',
    },
    {
      id: 'imm-tdap',
      title: 'Tetanus (Tdap)',
      last: 'Last: Aug 12, 2019',
      doses: '1 dose',
      status: 'Up to date',
      tone: 'green',
    },
  ],
  immunizationRecords: {
    alerts: [
      { id: 'imm-alert-flu', tone: 'warning', title: 'Overdue: Influenza (Seasonal)', detail: 'Scheduled for Oct 15, 2023' },
      { id: 'imm-alert-tdap', tone: 'info', title: 'Upcoming: Tdap Booster', detail: 'Due in 45 days (Dec 20, 2023)' },
      { id: 'imm-alert-travel', tone: 'neutral', title: 'Travel Vaccines', detail: 'Consultation recommended for upcoming trip.' },
    ],
    completed: [
      { id: 'imm-covid-3', vaccine: 'COVID-19 (Pfizer-BioNTech)', date: 'Aug 12, 2023', dose: 'Dose 3 (Booster)', provider: 'Dr. Sarah Jenkins', route: 'Left Deltoid / IM' },
      { id: 'imm-hepb-3', vaccine: 'Hepatitis B (Recombinant)', date: 'Jan 15, 2023', dose: '3 of 3', provider: 'Clinic Nurse A. Chen', route: 'Right Deltoid / IM' },
      { id: 'imm-hepb-2', vaccine: 'Hepatitis B (Recombinant)', date: 'Dec 10, 2022', dose: '2 of 3', provider: 'Clinic Nurse A. Chen', route: 'Left Deltoid / IM' },
      { id: 'imm-hepb-1', vaccine: 'Hepatitis B (Recombinant)', date: 'Nov 05, 2022', dose: '1 of 3', provider: 'Dr. Marcus Thorne', route: 'Right Deltoid / IM' },
      { id: 'imm-mmr', vaccine: 'MMR (Measles, Mumps, Rubella)', date: 'Jun 22, 2018', dose: 'Booster', provider: 'Central Health Clinic', route: 'Subcutaneous' },
      { id: 'imm-varicella', vaccine: 'Varicella', date: 'Apr 14, 2018', dose: '1 of 1', provider: 'Central Health Clinic', route: 'Subcutaneous' },
      { id: 'imm-flu-2022', vaccine: 'Influenza (Seasonal)', date: 'Oct 20, 2022', dose: 'Annual', provider: 'Walgreens Pharmacy', route: 'Left Deltoid / IM' },
      { id: 'imm-td-2014', vaccine: 'Tetanus/Diphtheria (Td)', date: 'Sep 10, 2014', dose: 'Booster', provider: 'City Hospital', route: 'Right Deltoid / IM' },
    ],
    compliance: {
      percent: 85,
      completed: 11,
      recommended: 13,
      detail: 'You are up to date with 11 out of 13 recommended adult immunizations.',
    },
  },
  educationalResources: {
    featured: {
      id: 'resource-hypertension-guide',
      category: 'Condition Focus',
      title: 'Managing Hypertension: A Comprehensive Daily Guide',
      detail: 'Based on your latest blood pressure readings (145/92 mmHg), this guide offers actionable steps for diet, exercise, and medication adherence.',
      meta: '12 min read',
      updated: 'Updated 2 days ago',
      actionLabel: 'Read Guide',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCMfqWfG-QA2INw_Eo4vXKMi-vPlVtKP7QtEoli50YCFKGOgszyurpo1W7Z5EB5cJO2zJhIZRZPsbP7Umh6ewEbjGEX2zgdAdmKkXU0EvaYkfRvxsjW4bx1Fz6PO5quvKAB9psp5LoprVaaFmoKMnHG02rIhuLqDD_pXVFEMkQAlIxJqjLRYx2P7hys7X9-iiopk0GZ26WudjQuuCHOWGK2C1_1QUTqX5JwKy_qyKX5gx2gSEZbASSglvQz8ambyGbbmkqu5Wu12SG',
    },
    video: {
      id: 'resource-lipid-video',
      title: 'Understanding Your Lipid Panel Results',
      detail: 'A visual walkthrough of what HDL, LDL, and Triglycerides mean for your heart health.',
      duration: '04:15',
      category: 'Video Tutorial',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBPptj0e2w8fwLXdAIJf583WykXafGGKMaOHkKVgm84ceqn7Kn6Bm1vrW7M58d8kZHjDxSQosvR4lnPblM-pEB7p7748U33wnUW-J_a2SwCa7KSt3y9PYn-WiXZoMmmjamysebYPIBtM66ud0eAGFpgijGwU-yMpdFes-BsiTaFlS3iwGb8Hd6qwhuqaRdx5IXLbWzms7RkPuS9Ydc7M7yVgbZLOFEDUYcR9IKZPjxZU0pyWNxnQ5neN1JONsFGXhsRcW9bEn0T5EqD',
    },
    groups: [
      {
        id: 'condition-guides',
        title: 'Condition Guides',
        items: [
          { title: 'Type 2 Diabetes Basics', detail: 'A starter kit for newly diagnosed patients.', action: 'Read Article' },
          { title: 'Managing Chronic Pain', detail: 'Evidence-based non-pharmaceutical options.', action: 'Read Article' },
          { title: 'Kidney Health 101', detail: 'Understanding GFR and hydration requirements.', action: 'Read Article' },
        ],
      },
      {
        id: 'medication-info',
        title: 'Medication Info',
        items: [
          { title: 'Statins: Benefits vs. Risks', detail: 'Addressing common concerns about muscle pain.', action: 'View Guide' },
          { title: 'Blood Thinners Safely', detail: 'Dietary restrictions and warning signs to watch.', action: 'View Guide' },
          { title: 'Antibiotic Stewardship', detail: 'Why completing the full course is critical.', action: 'View Guide' },
        ],
      },
      {
        id: 'wellness-tips',
        title: 'Wellness Tips',
        items: [
          { title: 'Anti-Inflammatory Diet', detail: 'Top 10 foods to help reduce swelling naturally.', action: 'Learn More' },
          { title: 'Sleep Hygiene Protocol', detail: 'Improving rest for better immune function.', action: 'Learn More' },
          { title: 'Stress Management 101', detail: 'Mindfulness techniques for clinical anxiety.', action: 'Learn More' },
        ],
      },
    ],
    library: [
      { id: 'lib-cbc', title: 'Understanding Lab Results: CBC Panel', detail: 'A detailed guide on red and white blood cell counts.', category: 'Diagnostics', updated: 'Oct 12, 2023', format: 'Article' },
      { id: 'lib-cardio', title: 'Low-Impact Cardio for Joint Health', detail: '15-minute home workout designed for arthritis patients.', category: 'Physical Therapy', updated: 'Nov 02, 2023', format: 'Video' },
      { id: 'lib-wound', title: 'Post-Operative Wound Care', detail: 'Essential steps for home care and identifying infection.', category: 'Surgery Recovery', updated: 'Sep 28, 2023', format: 'PDF' },
    ],
  },
  referrals: {
    summary: { active: 12, pending: 3, completedYear: 8 },
    rows: [
      { id: 'ref-9923', issuedDate: 'Oct 24, 2023', provider: 'Dr. Sarah Jenkins', specialty: 'Cardiology', reason: 'Echocardiogram follow-up post hypertension review', status: 'Pending', actions: ['Details', 'Contact'] },
      { id: 'ref-8841', issuedDate: 'Oct 12, 2023', provider: 'Dr. Aris Thorne', specialty: 'Dermatology', reason: 'Skin biopsy (Left forearm lesion)', status: 'Scheduled', actions: ['View Calendar'], appointment: 'Appt: Nov 05' },
      { id: 'ref-7220', issuedDate: 'Sep 28, 2023', provider: 'City General Imaging', specialty: 'Radiology', reason: 'Standard MRI - Cranial without contrast', status: 'Completed', actions: ['View Results'] },
      { id: 'ref-6119', issuedDate: 'Sep 15, 2023', provider: 'Dr. Lydia Vance', specialty: 'Endocrinology', reason: 'T1D Management review', status: 'Pending', actions: ['Resend Request'] },
    ],
    focus: {
      caseId: 'REF-9923',
      title: 'Referral Detail Focus',
      note: '"Patient presents with chronic hypertension. Referral to Cardiology is imperative for diagnostic imaging and baseline assessment of cardiac function. Priority: Routine."',
      attachment: 'Initial_Lab_Results.pdf',
      lastUpdate: 'Yesterday, 04:30 PM',
      clinic: 'Metro Health Cardiology',
      address: '122 Medical Plaza, Ste 400',
      phone: '(555) 010-8892',
      email: 'referrals@metrocardio.org',
    },
  },
  familyAccess: {
    proxies: [
      { id: 'proxy-sarah', name: 'Sarah Johnson', relationship: 'Spouse', permissions: 'Full Access', status: 'Active' },
      { id: 'proxy-michael', name: 'Michael Johnson', relationship: 'Adult Child', permissions: 'View Only', status: 'Active' },
      { id: 'proxy-david', name: 'David Reed', relationship: 'Legal Proxy', permissions: 'Awaiting Acceptance', status: 'Invitation Pending' },
    ],
    accounts: [
      { id: 'acct-emma', name: 'Emma Johnson', detail: 'Minor Child - Last Visit: Oct 12', access: 'Full Access' },
      { id: 'acct-robert', name: 'Robert Smith', detail: 'Elderly Parent - Last Visit: Nov 05', access: 'View Only' },
    ],
    activity: [
      { id: 'access-sarah', title: 'Sarah Johnson logged in', detail: 'Today, 09:12 AM - Viewed Lab Results', tone: 'success' },
      { id: 'access-rx', title: 'New prescription view', detail: "Oct 24, 02:45 PM - Emma Johnson's Profile", tone: 'info' },
      { id: 'access-revoked', title: 'Access updated', detail: "Oct 20, 11:00 AM - Revoked 'Billing' for Michael J.", tone: 'neutral' },
    ],
  },
  healthTrends: {
    summary: {
      withinRange: 2,
      attentionRequired: 1,
      updates: ['Vitals updated today', 'Labs 2 days ago', 'Rx adherence: High', 'HR Variability: Normal'],
    },
    metrics: [
      { id: 'trend-bp', label: 'Blood Pressure', status: 'Elevated', latest: '138/88', unit: 'mmHg', averageLabel: 'Avg', average: '132/84', points: [74, 62, 69, 58, 52] },
      { id: 'trend-hr', label: 'Heart Rate', status: 'Stable', latest: '72', unit: 'BPM', averageLabel: 'Resting Avg', average: '70', points: [60, 64, 61, 63, 62] },
      { id: 'trend-weight', label: 'Weight', status: 'Decreasing', latest: '84.2', unit: 'kg', averageLabel: 'Baseline', average: '91.0', points: [40, 46, 53, 61, 70] },
    ],
    labComparison: [
      { parameter: 'HbA1c (%)', baseline: '6.8', current: '6.1', change: '-0.7 down', status: 'Normal' },
      { parameter: 'Creatinine (mg/dL)', baseline: '1.1', current: '1.2', change: '+0.1 up', status: 'Normal' },
      { parameter: 'LDL Cholesterol (mg/dL)', baseline: '142', current: '128', change: '-14 down', status: 'Elevated' },
      { parameter: 'ALT (U/L)', baseline: '22', current: '46', change: '+24 up', status: 'Attention' },
    ],
    goals: [
      { id: 'goal-weight', label: 'Weight Loss Target (82kg)', progress: 75 },
      { id: 'goal-ldl', label: 'LDL Target (<100mg/dL)', progress: 40 },
    ],
  },
  messages: [
    {
      id: 'msg-1',
      from: 'Dr. Sarah Jenkins',
      subject: 'Lab Results Follow-up',
      preview: 'I have reviewed your blood work from Monday.',
      time: '10:24 AM',
    },
    {
      id: 'msg-2',
      from: 'Nursing Team',
      subject: 'Prescription Refill Request',
      preview: 'Your request for Lipitor has been sent to the pharmacy team.',
      time: 'Yesterday',
    },
  ],
  messageConversations: [
    {
      id: 'conv-sarah-jenkins',
      participantName: 'Dr. Sarah Jenkins',
      participantRole: 'Internal Medicine',
      activeNow: true,
      subject: 'Lab Results Follow-up',
      preview: 'I have reviewed your blood work from Monday.',
      time: '10:24 AM',
      unread: false,
      resolved: false,
      messages: [
        {
          id: 'thread-msg-1',
          direction: 'outbound',
          body: 'Hello Dr. Jenkins, I received my blood test results on the portal this morning. Most values seem normal, but I noticed my LDL cholesterol is higher than it was last year. Should I be concerned or adjust my medication?',
          sentAtLabel: '9:15 AM',
          createdAt: '2024-10-14T09:15:00.000Z',
          read: true,
        },
        {
          id: 'thread-msg-2',
          direction: 'inbound',
          body: "I have reviewed your blood work from Monday and noticed the slight increase as well. At 142 mg/dL, it is above our target for you, but not in the critical range yet. I'd like to try adjusting your diet for the next 3 months before we consider increasing your Atorvastatin dosage.\n\nI've attached a Mediterranean diet guide that has shown great success with my patients. Let's schedule a follow-up lab in January.",
          sentAtLabel: '10:24 AM',
          createdAt: '2024-10-14T10:24:00.000Z',
          labReference: {
            label: 'Lab Result Reference',
            name: 'Lipid Panel (LDL)',
            value: '142 mg/dL',
          },
          attachment: {
            fileName: 'Dietary_Guidelines_Lipid_Control.pdf',
            size: '2.4 MB',
          },
        },
      ],
    },
    {
      id: 'conv-nursing-team',
      participantName: 'Nursing Team',
      participantRole: 'Care Coordination',
      activeNow: false,
      subject: 'Prescription Refill Request',
      preview: 'Your request for Lipitor has been sent to the pharmacy team.',
      time: 'Yesterday',
      unread: true,
      resolved: false,
      messages: [
        {
          id: 'thread-msg-3',
          direction: 'inbound',
          body: 'Your request for Lipitor has been sent to the pharmacy team. We will notify you when the refill is approved.',
          sentAtLabel: 'Yesterday',
          createdAt: '2024-10-13T14:18:00.000Z',
        },
      ],
    },
    {
      id: 'conv-michael-chen',
      participantName: 'Dr. Michael Chen',
      participantRole: 'Surgery',
      activeNow: false,
      subject: 'Follow-up: Surgery Prep',
      preview: 'Please remember to fast for 12 hours prior to your appointment.',
      time: 'Oct 12',
      unread: false,
      resolved: true,
      messages: [
        {
          id: 'thread-msg-4',
          direction: 'inbound',
          body: 'Please remember to fast for 12 hours prior to your appointment and bring your medication list.',
          sentAtLabel: 'Oct 12',
          createdAt: '2024-10-12T08:30:00.000Z',
        },
      ],
    },
    {
      id: 'conv-billing',
      participantName: 'Billing Department',
      participantRole: 'Patient Accounts',
      activeNow: false,
      subject: 'Statement Available',
      preview: 'Your October billing statement is now available.',
      time: 'Oct 10',
      unread: false,
      resolved: false,
      messages: [
        {
          id: 'thread-msg-5',
          direction: 'inbound',
          body: 'Your October billing statement is now available in the patient portal.',
          sentAtLabel: 'Oct 10',
          createdAt: '2024-10-10T11:00:00.000Z',
        },
      ],
    },
  ],
  documents: [
    {
      id: 'doc-1',
      name: 'Continuity of care document',
      category: 'Summary',
      updated: 'May 29, 2026',
      status: 'Ready',
    },
    {
      id: 'doc-2',
      name: 'A1c laboratory report',
      category: 'Labs',
      updated: 'May 27, 2026',
      status: 'New',
    },
  ],
};
